# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

def one_signal
    pod 'OneSignal'
end

target 'MeterAI' do
  one_signal
  pod 'IQKeyboardManagerSwift'
  pod 'Charts'
  pod 'lottie-ios', '~> 3.1.3'
  pod 'Kingfisher', '~> 7.0'
  pod 'CryptoSwift', '~> 1.4.0'
  pod 'JNKeychain'
end

target 'OneSignalNotificationServiceExtension' do  
   one_signal
end